### ISSUE TITLE
screen / gesture orientation (espressowifi)

### ISSUE THREAD

**Issue by sobew** [yacuken/droid-config-espresso3g#1]
thank you / bolshoe spasibo for making this available.
i have installed it on espressowifi (note: p3113 wifi! not 3g!):

    espresso-common_TWRP_3.0.2-8.img
    cm-12.1-20161108-1918-UNOFFICIAL-espressowifi.zip
    freecyngn-flashable-cm12.zip
    sailfishos-espresso3g-release-2.0.5.6-alpha4.zip

it works quite well.  the main issue is that touchscreen / gestures are rotated 90degrees counter clockwise relative to screen (tap lower left instead of upper left to go back 1 menu).  i see there may be a similar xda comment (2 Nov, 8 Nov).
this happens for any settings -> display - orientation dynamic, landscape, portrait.
can you suggest a userland command to correct this?  or would i have to rebuild the whole adaptation?
i have not found any closely related variables:

    $ dconf read /lipstick/screen/primary/width
    1024
    $ dconf read /lipstick/screen/primary/height
    600
    
i did not test the cm12.1 operation before flashing sfos, but i have tested it on another espressowifi, and the cm orientation was correct.  i did have this problem in cm with an earlier version (cm-12.1-20161007-1359-UNOFFICIAL-espressowifi.zip)

i could test using cm-espresso3g if that would be useful to you.

**Comment by yacuken** [comment]
Hi @sobew 
Can you paste output from...
```
getprop | grep variant
```
and
```
cat /sys/devices/virtual/sec/tsp/pivot
```
?
And if value of `/sys/devices/virtual/sec/tsp/pivot` != 0 set it. And try again.

**Comment by sobew** [comment]
$ getprop | grep variant
    [init.svc.variant_setup]: [stopped]
    $ cat /sys/devices/virtual/sec/tsp/pivot
    1
    # echo 0 > /sys/devices/virtual/sec/tsp/pivot

that does improve it somewhat - but now must need to recalibrate touchscreen?
(it also seems to confuse the portrait / landscape orientation - sometimes.)
i now have to tap 1cm below and to the right of the white dot upper left screen corner to go back 1 menu.

in landscape orientation, accessing Settings:
in order to enter Display submenu
i have to tap 1cm right of Events view
the lowest Display entry i can access is Keep display on while charging
by tapping the very bottom (< 1cm) of the screen (anywhere on the left 60% or so).
i cannot access the lowest entry Orientation Dynamic.

note to self: this setting does not survive reboot.

if it would be more useful to you i could try to directly install the cm-espresso3g.
in further testing of my current wifi install, i find i don't seem to be able to power down the system (via icon after power button press or via # poweroff) even though i see the Goodbye splash screen - the battery drains regardless.  sometimes i also get the try a different charger message when plugging in charger.  but charging does seem to work, but is slow, even with a hi-amp charger.

**Comment by yacuken** [comment]
it doesn't matter wifi or 3g variant. bug in touchscreen (different controllers for 7" and 10"). I need 7" tab for tests.
I'll grab my 7" tab on next week. and then ping you.
also shutdown and reboot doesn't work from sfos :( as a workaround you can use android utils for it
```
/system/bin/reboot -p (for poweroff)
```

**Comment by sobew** [comment]
thank you for valuable information

here are some random display-related items from journalctl

    Dec 13 18:50:11 Sailfish lipstick[710]: [D] HwComposerScreenInfo::HwComposerScreenInfo:251 - EGLFS: Screen Info
    Dec 13 18:50:11 Sailfish lipstick[710]: [D] HwComposerScreenInfo::HwComposerScreenInfo:252 -  - Physical size: QSizeF(154, 90)
    Dec 13 18:50:11 Sailfish lipstick[710]: [D] HwComposerScreenInfo::HwComposerScreenInfo:253 -  - Screen size: QSize(1024, 600)
    Dec 13 18:50:11 Sailfish lipstick[710]: [D] HwComposerScreenInfo::HwComposerScreenInfo:254 -  - Screen depth: 32
    ...
    Dec 13 18:50:46 Sailfish [880]: [W] DeclarativeWindow::DeclarativeWindow:9
    4 - No default allowed orientations defined. Check your device configuration!

dmesg is not of much use. it fills up with

    [10456.256713] cbd: /main: Modem type = 1
    [10456.257171] cbd: /main: Boot link = 0
    [10456.257415] cbd: /main: Main link = 0
    [10457.261413] cbd: /main: Modem type = 1

maybe due to lack of ril on wifi?

    Dec 14 07:07:04 Sailfish ofonod[603]: [grilio] ERROR! Can't connect to RILD: No such file or directory

repeats every 2 seconds.  stopping ofono.service does stop journal messages, but not dmesgs

**Comment by yacuken** [comment]
try add `disabled` to `cpboot-daemon` in /init.espresso.rc
```
service cpboot-daemon /sbin/cbd -d -p 8
    class main
    user root
    group radio cache inet misc audio sdcard_rw log sdcard_r
    seclabel u:r:cpboot-daemon:s0
    disabled
```

**Comment by sobew** [comment]
thank you. this does clean up log messages.
there is a kernel trace omap_hwmod: uart3  (unrelated to orientation i guess).
if any of this output would be useful or should be reported as an issue let me know.
i will otherwise keep testing different features.



---- On Tue, 13 Dec 2016 22:12:54 -0800 Nikita &lt;notifications@github.com&gt; wrote ---- 

try add disabled to cpboot-daemon in /init.espresso.rc
 service cpboot-daemon /sbin/cbd -d -p 8 class main user root group radio cache inet misc audio sdcard_rw log sdcard_r seclabel u:r:cpboot-daemon:s0 disabled  —
