### ISSUE TITLE
Query about touchscreen orientation issue status ?

### ISSUE THREAD

**Issue by adeen-s** [yacuken/droid-config-espresso3g#2]
In my SFOS build for espresso3g, I encountered a weird issue where the touchscreen and the display were perpendicular relative to each other. Is it the same in your build or has it been fixed ? 

Did you encounter it in the first place? What steps did you take to fix it if it ever got fixed ?

Thanks.

**Comment by MightyM17** [comment]
@adeen-s Sorry im late to answer the question but the xda thread has a fix for it https://forum.xda-developers.com/t/sfos-dev-only-sailfish-os-for-galaxy-tab-2-3g.3429786/post-70366418

**Comment by adeen-s** [comment]
Hey @MightyM17, thanks. 

Yeah, I was able to find a solution to this eventually. 
Thanks though. I think I should close this issue now.

**Comment by MightyM17** [comment]
> Hey @MightyM17, thanks.
> 
> Yeah, I was able to find a solution to this eventually.
> Thanks though. I think I should close this issue now.

Sorry for retalking here @adeen-s, but have u made sfos for the tab 2? I just made one and it works properly but i have some questions

**Comment by adeen-s** [comment]
Yeah @MightyM17, I was able to get it running with some bugs. It was almost 4 years ago though, so I don't remember much. 
But you can check out the droid config repo on my GitHub account for espresso3g iirc.

**Comment by MightyM17** [comment]
> Yeah @MightyM17, I was able to get it running with some bugs. It was almost 4 years ago though, so I don't remember much.
> But you can check out the droid config repo on my GitHub account for espresso3g iirc.

Alrighty! https://forum.xda-developers.com/t/sailfishos-3-on-galaxy-tab-2.4230841/ got it working but with cm13 base. Nougat seems really bugged :(
